# Generated by Django 3.0.5 on 2020-04-08 14:21

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200407_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='description',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
