# Generated by Django 3.0.5 on 2020-04-10 12:56

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=froala_editor.fields.FroalaField(default=None),
            preserve_default=False,
        ),
    ]
